version: '3.9'
services:
  user_backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db_user

# wrong config
  db_user:
    # image: mysql
    # restart: always
    # environment:
    #   - MYSQL_DATABASE=${MYSQL_DATABASE}
    #   - MYSQL_USER=${MYSQL_USER}
    #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #   - MYSQL_HOST=${MYSQL_HOST}
    #   - MYSQL_PORT=${MYSQL_PORT}
    #   - MYSQL_ROOT_PASSWORD=root
    #   - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    # volumes:
    #   - .dbdata:/var/lib/mysql
    # expose:
    #   - 33066
    # ports:
    #   - 33066:3306
